language: php
php:
  - "5.5"
before_script:
  # apache
  - ./install-dependencies.sh
  - ./install-wp-tests.sh
  # mysql
  - mysqladmin create wordpress_test --user=root
  - cp resources/.env .
  - composer install -vv
  - curl 127.0.0.1
  - curl 127.0.0.1/wp
  - curl 127.0.0.1/selenium.sh
  - ./selenium.sh
  - mkdir -p build/logs
script:
  - curl -s http://localhost/ && sudo cat /var/log/apache2/error.log && curl -s http://localhost/ | grep -F "hello world! $TRAVIS_PHP_VERSION" && curl -s http://localhost/non_existing_url_is_redirected | grep -F "hello world! $TRAVIS_PHP_VERSION" && curl -s http://mydomain.local/ | grep -F "hello world! $TRAVIS_PHP_VERSION"
  - composer behat
