language: php
php:
  - 5.5
before_script:
  #apache
  - sudo apt-get update 2>/dev/null
  - sudo apt-get install apache2 libapache2-mod-fastcgi # php5-mysql
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f resources/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  #mysql
  - mysqladmin create wordpress_test --user=root
  - cp resources/.env .
  - composer install -vv
  - curl 127.0.0.1
  - curl 127.0.0.1/wp
  - curl 127.0.0.1/selenium.sh
  - ./selenium.sh
  - mkdir -p build/logs
script:
  - composer behat
