language: php
php:
  - 5.6
before_script:
  - sudo ./apachetravis.sh
  #mysql
  - mysqladmin create wordpress_test --user=root
  - cp resources/.env .
  - composer install -vv
  - curl 127.0.0.1
  - curl 127.0.0.1/wp
  - curl 127.0.0.1/selenium.sh
  - ./selenium.sh
  - mkdir -p build/logs
script:
  - composer behat
