language: php
sudo: require
php:
  - "5.5"
cache:
  - apt
env:
  - HOSPITAL_HOST="http://127.0.0.1" HTTP_HOST="http://127.0.0.1" DB_HOST=127.0.0.1 DB_NAME=hospital DB_USER=root DB_PASSWORD=
before_script:
  - scripts/install-server.sh
  - scripts/install-dependencies.sh
  - scripts/install-wp-cli.sh
  - cp resources/.env.travis .env
  - scripts/install-wp-all.sh
#  - scripts/install-wp-tests.sh wordpress_test root '' localhost latest
  - scripts/selenium.sh
#  - mkdir -p build/logs
script:
#  - phpunit -c phpunit-wpdb.xml
  - phpunit -c phpunit-integration.xml
- composer behat
after_script:
  - curl http://127.0.0.1/wp/
  - curl http://127.0.0.1/wp/wp-admin/
