language: php
php:
  - 5.6
before_script:
  - ./scripts/apachetravis.sh
  #mysql
  - mysqladmin create wordpress_test --user=root
  - cp resources/.env .
  - composer install -vvv
  - curl 127.0.0.1/wp-admin
  - ./selenium.sh
  - mkdir -p build/logs
script:
  - composer behat
