language: php
php:
  - "5.5"
env:
  - HOSPITAL_HOST="http://127.0.0.1"
  - HTTP_HOST="http://127.0.0.1"
  - DB_HOST=127.0.0.1
  - DB_NAME=hospital
  - DB_USER=root
  - DB_PASSWORD=
before_script:
  - scripts/install-server.sh
  - scripts/install-dependencies.sh
#  - cp resources/.env .
#  - cp resources/.env ~
  - wp db create
  - scripts/install-wp-tests.sh wordpress_test root '' localhost latest
  - scripts/selenium.sh
  - mkdir -p build/logs
script:
  - phpunit -c phpunit-wpdb.xml
  - curl -s http://localhost/ && sudo cat /var/log/apache2/error.log && curl -s http://localhost/ | grep -F "hello world! $TRAVIS_PHP_VERSION" && curl -s http://localhost/non_existing_url_is_redirected | grep -F "hello world! $TRAVIS_PHP_VERSION" && curl -s http://mydomain.local/ | grep -F "hello world! $TRAVIS_PHP_VERSION"
  - composer behat
after_script:
  - curl 127.0.0.1
  - curl 127.0.0.1/wp
  - curl 127.0.0.1/selenium.sh
  
