# Site settings
title: HospitalPage
#email: zxc@qwe
description: "Opis projektu."
baseurl: "/hospitalpage"
url: "https://hospitalhub.github.io"
github_username:  hospitalhub
timezone: Europe/Warsaw

# Build settings
markdown: kramdown
permalink: pretty
