# Site settings
title: HospitalPage
email: zxc@qwe
description: "Opis projektu."
baseurl: "/hospitalpage"
url: "http://github.com/hospitalhub"
github_username:  hospitalhub

# Build settings
markdown: kramdown
permalink: pretty
